repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
        name: isort (python)

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
      args: [--config=pyproject.toml]
      language_version: python3.11

-   repo: https://github.com/klen/pylama
    rev: 8.4.1
    hooks:
    - id: pylama
      args:
        - "--ignore=D203,D212,E203,C901"
